
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_Segment(

	//////////// CLOCK //////////

	input 		          		MAX10_CLK1_50,
	input                       MAX10_rst_n,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,


	//////////// LED //////////
	output		     [3:0]		LEDR,

	//////////// SW //////////
	input 		     [3:0]		SW
);

//PLL initiation
wire clk_12m5;
wire clk_25m;
wire clk_50m;
wire clk_100m;
wire sys_rst_n;

pll	pll_inst (
	.areset ( !MAX10_rst_n),
	.inclk0 ( MAX10_CLK1_50),
	.c0 ( clk_12m5 ),
	.c1 ( clk_25m ),
	.c2 ( clk_50m ),
	.c3 ( clk_100m),
	.locked ( sys_rst_n )
	);

wire[15:0] display_num;

counter uut_counter(
	.clk(clk_25m),
	.rst_n(sys_rst_n),
	.display_num(display_num)
	);
	
//---------------------------------------------
// driving 4bits digital segment
segment uut_segment(
	.clk(clk_25m),
	.rst_n(sys_rst_n),
	.display_num(display_num),
	.switch(SW),
	.dseg_led(LEDR),
	.HEX0(HEX0),
	.HEX1(HEX1),
	.HEX2(HEX2),
	.HEX3(HEX3),
);


endmodule
